version: 2.0

references:

  workspace_root: &workspace_root
    ./

  node_container: &node_container
    docker:
      - image: circleci/node:8.10

  attach_workspace: &attach_workspace
    attach_workspace:
      at: *workspace_root

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - *attach_workspace
      - run: npm ci
      - run: npm run build
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - data.json
            - node_modules
  test:
    <<: *node_container
    steps:
      - checkout
      - *attach_workspace
      - run: npm ci
      - run: npm test

workflows:
  version: 2
  default:
    jobs:
      - build
      - test:
          requires: [ 'build' ]