version: 2.1

jobs:
  test:
    docker:
      - image: circleci/node:8.10
    steps:
      - checkout
      - run: npm i
      - run: npm test
      - run: npm run build
      - run: cmp data.tmp.json data.json

workflows:
  version: 2
  default:
    jobs:
      - test:
          context: aws-ssm-readonly
